name: deleteUntaggedImages

on:
  workflow_run:
    workflows: ['buildAndPushImage']
    types: [completed]

env:
  PACKAGE_NAME: analysis-manager
  PACKAGE_TYPE: container

jobs:
  delete-untagged-images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          #owner: ${{ github.repository_owner }}
          package-name: ${{ PACKAGE_NAME }}
          package-type: ${{ PACKAGE_TYPE }}
          #token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"